### ISSUE TITLE
Add send scheduled message

### ISSUE THREAD

**Issue by fulviodenza** [SakoDroid/telego#16]
Hi, is it possible to add the schedule_date flag to the SendMessage method?
As it appears from [here](https://core.telegram.org/api/scheduled-messages#:~:text=To%20schedule%20a%20message%2C%20simply,sent%20at%20the%20specified%20time.) , it looks that the api provides this feature.

**Comment by SakoDroid** [comment]
Hi @fulviodenza , hope you are doing well.
The page you provided is related to telegram main APIs which is used for user chats. (They call it user APIs).
The bot APIs do not provide such a thing. This page [here](https://core.telegram.org/bots/api)  is bot APIs.

**Comment by fulviodenza** [comment]
I suppose a job scheduler will be a workaround, thank you anyway!

**Comment by SakoDroid** [comment]
@fulviodenza 
You're welcome of course.
What you mentioned could be an approach but we need to keep in mind that such thing would need a local database to keep track of the scheduled messages in case of an app restart.

Maybe this option will be added in the future. There are some great updates on the way!

**Comment by fulviodenza** [comment]
I've implemented the beta feature for this in this exact moment as you can see from the pipeline ahahah (https://github.com/fulviodenza/pills-of-cs).
Anyway my bot already requires to keep track of user preferences for their tags, so it's not an issue having the database

**Comment by SakoDroid** [comment]
Wow that's nice work, well done.

I agree with you maybe you can add this feature but i'm still not sure about it. (Al tough your help is much appreciated) . This feature should be left out for the developer to implement the way they see fit.
